#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx for redirection and custom 404 page
sudo bash -c 'cat > /etc/nginx/sites-enabled/default <<EOL
server {
    listen 80 default_server;

    root /var/www/html;
    index index.html;

    location /redirect_me {
        rewrite ^ https://www.facebook.com permanent;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}
EOL'

sudo service nginx restart

