#!/usr/bin/env bash

# Install HAProxy
apt-get update
apt-get -y install haproxy

# Load balancer configuration
DOMAIN_NAME='willardmasarat.tech'
INIT_FILE='/etc/default/haproxy'
CONFIG_FILE='/etc/haproxy/haproxy.cfg'
HAPROXY_LB_CONFIG="
#--$DOMAIN_NAME-params-begin--
backend $DOMAIN_NAME-backend
    balance roundrobin
    server 376189-web-01 52.91.152.105:80 check
    server 376189-web-02 100.25.36.62:80 check

frontend $DOMAIN_NAME-frontend
    bind *:80
    mode http
    default_backend $DOMAIN_NAME-backend
#--$DOMAIN_NAME-params-end--
"

# Ensure configuration files exist
[ -f "$INIT_FILE" ] || touch "$INIT_FILE"
[ -f "$CONFIG_FILE" ] || touch "$CONFIG_FILE"

# Enable HAProxy
if ! grep -q '^ENABLED=[01]$' "$INIT_FILE"; then
    echo 'ENABLED=1' >> "$INIT_FILE"
fi

# Configure HAProxy
if ! grep -q "$DOMAIN_NAME-backend" "$CONFIG_FILE"; then
    echo -e "$HAPROXY_LB_CONFIG" >> "$CONFIG_FILE"
else
    start_tkn="#--$DOMAIN_NAME-params-begin--"
    end_tkn="#--$DOMAIN_NAME-params-end--"
    a=$(grep -onE "$start_tkn" "$CONFIG_FILE" | cut -d : -f1)
    b=$(grep -onE "$end_tkn" "$CONFIG_FILE" | cut -d : -f1)
    a=$((a - 1))
    b=$((b + 1))
    sed -i "$a,$b"d "$CONFIG_FILE"
    echo -en "$HAPROXY_LB_CONFIG" >> "$CONFIG_FILE"
fi

# Restart or start HAProxy service
if ! pgrep -x "haproxy" > /dev/null; then
    service haproxy start
else
    service haproxy restart
fi


