#!/usr/bin/env bash
# Bash script that handles signals and creates a PID file.

# Create PID file
echo $$ > /var/run/myscript.pid

# Signal handlers
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT SIGTERM

# Looping indefinitely
while true
do
    echo "To infinity and beyond"
    sleep 2
done

