#!/usr/bin/env bash
# change of localhost

if [ "$EUID" -ne 0 ]; then
    echo "This script must be run with superuser privileges."
    exit 1
fi

# Modify /etc/hosts file to configure DNS resolution
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
